sudo: required
services: 
  - docker
before_install:
  - docker build -t react -f Dockerfile.dev .
script:
  - docker run react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react"
  env: "React-env"
  bucket_name: "elasticbeanstalk-us-east-1-117155957847"
  bucket_path: "react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"